// <auto-generated />
namespace PerkyRabbit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class expenditure_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(expenditure_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202308260918558_expenditure_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
